# Generated by Django 4.2.4 on 2023-08-08 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('47dc9f7c-6ba7-40e2-8326-38391e15a386'), primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('school', models.TextField()),
                ('age', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
