# Generated by Django 4.2.3 on 2023-08-09 06:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c193a948-04e2-4315-ba68-66130c84c9fb'), primary_key=True, serialize=False),
        ),
    ]
