# Generated by Django 4.2.3 on 2023-08-09 06:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('96c633c9-27e4-442f-b5ab-b2c5aa575fc7'), primary_key=True, serialize=False),
        ),
    ]
